# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 08:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fit', '0002_fit_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='作業日')),
                ('start_time', models.DateTimeField(verbose_name='開始時刻')),
                ('end_time', models.DateTimeField(verbose_name='終了時刻')),
                ('comment', models.CharField(max_length=255, verbose_name='コメント')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
