# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0003_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='user',
        ),
        migrations.AlterField(
            model_name='work',
            name='comment',
            field=models.CharField(max_length=255, null=True, verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='work',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='終了時刻'),
        ),
        migrations.AlterField(
            model_name='work',
            name='start_time',
            field=models.DateTimeField(null=True, verbose_name='開始時刻'),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_date',
            field=models.DateField(null=True, verbose_name='作業日'),
        ),
    ]
