# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0004_auto_20180107_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='id',
        ),
        migrations.AlterField(
            model_name='work',
            name='work_date',
            field=models.DateField(primary_key=True, serialize=False, verbose_name='作業日'),
        ),
    ]
