# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0006_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heart',
            fields=[
                ('heart_date', models.DateField(primary_key=True, serialize=False, verbose_name='作業日（心拍）')),
                ('heart_image_url', models.URLField(blank=True, verbose_name='心拍画像URL')),
            ],
        ),
    ]
