# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0007_heart'),
    ]

    operations = [
        migrations.AddField(
            model_name='heart',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='heart',
            name='heart_date',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fit.Work'),
        ),
    ]
