# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-23 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0008_auto_20180111_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work2',
            fields=[
                ('work_date', models.DateField(primary_key=True, serialize=False, verbose_name='作業日')),
                ('start_time', models.DateTimeField(blank=True, verbose_name='開始時刻')),
                ('end_time', models.DateTimeField(blank=True, verbose_name='終了時刻')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='コメント')),
            ],
        ),
    ]
