# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-23 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0009_work2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work2',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='終了時刻'),
        ),
        migrations.AlterField(
            model_name='work2',
            name='start_time',
            field=models.DateTimeField(null=True, verbose_name='開始時刻'),
        ),
    ]
