# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-24 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0010_auto_20180123_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heart2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_image_url', models.URLField(blank=True, verbose_name='心拍画像URL')),
                ('heart_date', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fit.Work2')),
            ],
        ),
    ]
