# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-27 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0012_auto_20180127_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heart3',
            name='heart_date',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fit.Work2'),
        ),
    ]
