# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-28 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0014_auto_20180127_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heart4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.DateField(blank=True, verbose_name='イメージid')),
                ('heart_image_url', models.URLField(blank=True, verbose_name='心拍画像URL')),
                ('heart_date', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fit.Work2')),
                ('heart_sleep', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fit.Sleep')),
            ],
        ),
    ]
