# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-28 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0015_heart4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heart3',
            name='heart_date',
        ),
        migrations.DeleteModel(
            name='Heart3',
        ),
    ]
