# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-28 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0016_auto_20180128_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heart4',
            name='heart_date',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fit.Work3'),
        ),
    ]
